In [24]:
import torch

# torch.take

In [25]:
src = torch.arange(1, 11).reshape(2, 5)
print("原始输入")
print(src)
print("取索引为0、2、5方面的值")
print(torch.take(src,torch.tensor([0, 2, 5])))

原始输入
tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])
取索引为0、2、5方面的值
tensor([1, 3, 6])


# torch.tile


In [26]:
a = torch.rand([4,3])
print("原始输入")
print(a)

print("对行复制2份")
a_tiled = torch.tile(a,[2,1])
print(a_tiled)

print("对列复制2份")
b_tiled = torch.tile(a,[1,2])
print(b_tiled)

原始输入
tensor([[0.4231, 0.4308, 0.8707],
        [0.1037, 0.9457, 0.7375],
        [0.5500, 0.7777, 0.3454],
        [0.0587, 0.9838, 0.5693]])
对行复制2份
tensor([[0.4231, 0.4308, 0.8707],
        [0.1037, 0.9457, 0.7375],
        [0.5500, 0.7777, 0.3454],
        [0.0587, 0.9838, 0.5693],
        [0.4231, 0.4308, 0.8707],
        [0.1037, 0.9457, 0.7375],
        [0.5500, 0.7777, 0.3454],
        [0.0587, 0.9838, 0.5693]])
对列复制2份
tensor([[0.4231, 0.4308, 0.8707, 0.4231, 0.4308, 0.8707],
        [0.1037, 0.9457, 0.7375, 0.1037, 0.9457, 0.7375],
        [0.5500, 0.7777, 0.3454, 0.5500, 0.7777, 0.3454],
        [0.0587, 0.9838, 0.5693, 0.0587, 0.9838, 0.5693]])


# torch.transpose

In [27]:
a = torch.rand([4,3])
print("原始输入")
print(a)
print("矩阵转置")
b = torch.transpose(a,0,1)
print(b)

原始输入
tensor([[0.8382, 0.2122, 0.0416],
        [0.4322, 0.3460, 0.4350],
        [0.5954, 0.9417, 0.2092],
        [0.8786, 0.7743, 0.3844]])
矩阵转置
tensor([[0.8382, 0.4322, 0.5954, 0.8786],
        [0.2122, 0.3460, 0.9417, 0.7743],
        [0.0416, 0.4350, 0.2092, 0.3844]])


# torch.unbind

In [28]:
print("原始张量")
t = torch.rand([4,3])# 正太分布
print(t)
unbind_t1,unbind_t2,unbind_t3,unbind_t4= torch.unbind(t,dim=0) 

print("沿着 0 维度 解绑后的张量")
print(unbind_t1)
print(unbind_t2)
print(unbind_t3)
print(unbind_t4)

unbind_t1,unbind_t2,unbind_t3= torch.unbind(t,dim=1) 


print("沿着 1 维度 解绑后的张量")
print(unbind_t1)
print(unbind_t2)
print(unbind_t3)

print("3维张量")
t = torch.rand([2,3,4])
print("原始输入")
print(t)
print("沿着 0 维度 解绑后的张量")
unbind_t1,unbind_t2= torch.unbind(t,dim=0) 
print(unbind_t1)
print(unbind_t2)

原始张量
tensor([[0.0678, 0.7744, 0.2543],
        [0.4660, 0.2238, 0.7283],
        [0.0984, 0.9216, 0.5059],
        [0.5221, 0.1730, 0.2826]])
沿着 0 维度 解绑后的张量
tensor([0.0678, 0.7744, 0.2543])
tensor([0.4660, 0.2238, 0.7283])
tensor([0.0984, 0.9216, 0.5059])
tensor([0.5221, 0.1730, 0.2826])
沿着 1 维度 解绑后的张量
tensor([0.0678, 0.4660, 0.0984, 0.5221])
tensor([0.7744, 0.2238, 0.9216, 0.1730])
tensor([0.2543, 0.7283, 0.5059, 0.2826])
3维张量
原始输入
tensor([[[0.5715, 0.7657, 0.6000, 0.8430],
         [0.6568, 0.3840, 0.3456, 0.7582],
         [0.7608, 0.8801, 0.8398, 0.4249]],

        [[0.7610, 0.6894, 0.9941, 0.9839],
         [0.9273, 0.2136, 0.6359, 0.0452],
         [0.2692, 0.9333, 0.8010, 0.7149]]])
沿着 0 维度 解绑后的张量
tensor([[0.5715, 0.7657, 0.6000, 0.8430],
        [0.6568, 0.3840, 0.3456, 0.7582],
        [0.7608, 0.8801, 0.8398, 0.4249]])
tensor([[0.7610, 0.6894, 0.9941, 0.9839],
        [0.9273, 0.2136, 0.6359, 0.0452],
        [0.2692, 0.9333, 0.8010, 0.7149]])


# torch.unsqueeze

In [35]:
t = torch.tensor([1,2,3,4])
print("原始输入")
print(t.shape)
t = torch.unsqueeze(t,dim=0)
print("扩维后的张量")
print(t.shape)

print("----------------------------------------------------------------------")
t = torch.rand([2,3,4])
print(t.shape)
print(torch.unsqueeze(t,dim=0).shape)
print(torch.unsqueeze(t,dim=-1).shape)

原始输入
torch.Size([4])
扩维后的张量
torch.Size([1, 4])
----------------------------------------------------------------------
torch.Size([2, 3, 4])
torch.Size([1, 2, 3, 4])
torch.Size([2, 3, 4, 1])


# torch.where 三目运算符


In [36]:
x = torch.randn([3, 2]) #使用高斯分布进行随机
print(x)
y = torch.ones([3,2])
print(y)

print("x中整数的位置进行保存,负数的地方用1代替")
z = torch.where(x>0,x,y) 
print(z)

tensor([[ 1.0306, -0.1107],
        [ 0.8425, -0.6103],
        [-1.4706,  0.2547]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
x中整数的位置进行保存,负数的地方用1代替
tensor([[1.0306, 1.0000],
        [0.8425, 1.0000],
        [1.0000, 0.2547]])


In [37]:
a = torch.randn(2,2,dtype=torch.double)
print(a)
# b = torch.where(a>0,x,2.)
b = torch.where(a > 0, a, 2.)
print(b)

tensor([[ 1.0635, -0.6477],
        [ 0.0929, -0.9522]], dtype=torch.float64)
tensor([[1.0635, 2.0000],
        [0.0929, 2.0000]], dtype=torch.float64)


# torch.manual_seed 手动设置随机种子

In [38]:
a = torch.manual_seed(1)
print(a)

# torch.normal

In [46]:
print("从均值为2,方差为3的分布中采样一个1 * 4的矩阵")
t = torch.normal(2,3,size=(1,4))
print(t)

print("------------------------------------------------------------------------------------------------")
mean = torch.arange(1., 11.)
std = torch.arange(1, 0, -0.1)
print(Mean)
print(Std)
Gaussian = torch.normal(mean=mean, std=std)
print(Gaussian)

从均值为2,方差为3的分布中采样一个1 * 4的矩阵
tensor([[-2.7180,  1.6303, 12.7610, -3.4939]])
------------------------------------------------------------------------------------------------
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([1.0000, 0.9000, 0.8000, 0.7000, 0.6000, 0.5000, 0.4000, 0.3000, 0.2000,
        0.1000])
tensor([ 2.5987,  0.8507,  3.2604,  3.6646,  5.8274,  7.2643,  7.1643,  7.7036,
         8.8184, 10.0542])


# torch.roll  张量的循环滚动

In [45]:
print("------torch.roll算子默认的是向右和下循环滚动的------")
x = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8,9,10,11,12,13,14,15,16]).view(4, 4)

print("张量原始输入")
print(x)

print("将最后一列循环滚动到第一列来")
a1 = torch.roll(x,shifts=(1),dims=(1))
print(a1)
print("将第一列循环滚动到最后一列去")
a2 = torch.roll(x,shifts=(-1),dims=(1))
print(a2)


------torch.roll算子默认的是向右和下循环滚动的------
张量原始输入
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])
将最后一列循环滚动到第一列来
tensor([[ 4,  1,  2,  3],
        [ 8,  5,  6,  7],
        [12,  9, 10, 11],
        [16, 13, 14, 15]])
将第一列循环滚动到最后一列去
tensor([[ 2,  3,  4,  1],
        [ 6,  7,  8,  5],
        [10, 11, 12,  9],
        [14, 15, 16, 13]])


# torch.randperm

In [47]:
print("传入上界 并进行shuffle")
print(torch.randperm(4))

tensor([1, 0, 3, 2])
