# <font color = 'red'>Pytorch张量介绍 1</font>

In [11]:
import torch
import numpy as np

### 1.从列表中创建张量

In [12]:
data = [[1,2],[3,4.]]
x_data = torch.tensor(data)
print(x_data)


tensor([[1., 2.],
        [3., 4.]])


### 2.查看变量类型

In [13]:
print(type(data))
print(type(x_data))
print(x_data.dtype) # 打印Tensor类型

<class 'list'>
<class 'torch.Tensor'>
torch.float32


### 3.从numpy中创建tensor

In [51]:
a = np.random.normal((2,3))
print(a)
b = torch.tensor(a)
print(b)
print(type(a))
print(type(b))
print("---------------------------")
c = torch.ones_like(b)# 构建一个与b shape一致的全 1 tensor(基于已有张量)
print(c)
print(type(c))
print("---------------------------")

c = torch.zeros_like(b)# 构建一个与b shape一致的全 0 tensor(基于已有张量)
print(c)
print(type(c))
print("---------------------------")
c = torch.rand_like(b)# 构建一个与b shape一致的随机数 tensor(基于已有张量)
print(c)
print(type(c))

[2.39015423 1.8299572 ]
tensor([2.3902, 1.8300])
<class 'numpy.ndarray'>
<class 'torch.Tensor'>
---------------------------
tensor([1., 1.])
<class 'torch.Tensor'>
---------------------------
tensor([0., 0.])
<class 'torch.Tensor'>
---------------------------
tensor([0.7355, 0.7598])
<class 'torch.Tensor'>


### 4.一个2 * 2的随机张量

In [52]:
a = torch.rand([2,2],dtype=torch.float64)
print(a)
print(a.shape)
print(a.dtype)
print(a.device)

tensor([[0.2421, 0.8330],
        [0.2006, 0.5075]])
torch.Size([2, 2])
torch.float64
cpu


In [53]:
istensor = torch.is_tensor(a) # 判断是否是一个pytorch 的 tensor
print(istensor)

True


### 5.判断cuda是否可用

In [54]:
bCuda = torch.cuda.is_available()
print(bCuda)

False


### 6.判断张量是否是浮点类型:is_floating_point

In [55]:
np_array_int = [4,5,6]
tensor_array_int = torch.tensor(np_array_int)
print(tensor_array_int)
print(torch.is_floating_point(tensor_array_int)) # 输入必须是tensor

tensor([4, 5, 6])
False


### 7.是否是0的张量:is_nonzero

In [56]:
a = torch.tensor(1.0)
print(torch.is_nonzero(a))
b = torch.tensor(0.0)
print(torch.is_nonzero(b))

True
False


### 8.返回所有元素的数目:numel

In [57]:
a = torch.rand([2,2],dtype=torch.float64)
print(a.shape)
print(torch.numel(a))

torch.Size([2, 2])
4


# 9.全0,1张量:zeros,ones

In [60]:
a = torch.zeros((5,5))
print(a)
print(a.dtype)

a = torch.ones((5,5))
print(a)
print(a.dtype)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
torch.float64
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
torch.float64


### 10.设置全局默认类型:set_default_tensor_type

In [59]:

torch.set_default_tensor_type(torch.DoubleTensor)
a = torch.zeros((5,5))
print(a)
print(a.dtype)


tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
torch.float64


### 11.生成一个区间tensor:arange(左闭又开)

In [ ]:
print(torch.arange(start=4,end=10,step=2)) # 如果只转入一个边界 将会默认成end

### 12.生成一个区间tensor:arange(左闭又闭)

In [65]:
print(torch.range(start=0,end=5))

tensor([0., 1., 2., 3., 4., 5.])


/Users/yangrunze/opt/anaconda3/envs/py37/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  """Entry point for launching an IPython kernel.


### 13.创建一个对角线张量

In [69]:
print(torch.eye(5,6))
print(torch.eye(6))

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.]])
tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])


### 14.创建一个填充tensor:full


In [70]:
print(torch.full([2,2],10))

tensor([[10, 10],
        [10, 10]])


### 15.对两个tensor在指定维度进行连接:cat

In [73]:
a = torch.rand([10,5])
b = torch.rand([3,5])
c = torch.cat([a,b],dim=0)
print(a)
print("------------------------------------")
print(b)
print("------------------------------------")
print(c)

tensor([[0.7761, 0.8716, 0.8311, 0.3228, 0.3571],
        [0.7811, 0.8868, 0.7696, 0.0177, 0.8769],
        [0.1628, 0.1159, 0.7921, 0.6716, 0.4028],
        [0.3485, 0.1648, 0.7134, 0.3158, 0.7564],
        [0.8160, 0.6631, 0.1561, 0.4971, 0.8466],
        [0.4925, 0.9635, 0.7957, 0.5040, 0.4395],
        [0.0856, 0.6004, 0.1121, 0.6204, 0.7538],
        [0.1291, 0.0642, 0.5383, 0.7846, 0.8816],
        [0.6737, 0.1045, 0.9492, 0.0031, 0.9977],
        [0.9970, 0.5753, 0.3521, 0.0250, 0.5214]])
------------------------------------
tensor([[0.8099, 0.8733, 0.5531, 0.4308, 0.0212],
        [0.8512, 0.6576, 0.0072, 0.7883, 0.0978],
        [0.5406, 0.4226, 0.4241, 0.2395, 0.2492]])
------------------------------------
tensor([[0.7761, 0.8716, 0.8311, 0.3228, 0.3571],
        [0.7811, 0.8868, 0.7696, 0.0177, 0.8769],
        [0.1628, 0.1159, 0.7921, 0.6716, 0.4028],
        [0.3485, 0.1648, 0.7134, 0.3158, 0.7564],
        [0.8160, 0.6631, 0.1561, 0.4971, 0.8466],
        [0.4925, 0.9635,