In [2]:
import torch

In [3]:
# chunk
chunk_tesor = torch.rand([3,2])
print(chunk_tesor)
a = torch.chunk(chunk_tesor,chunks=2)
print(a)
b = torch.chunk(chunk_tesor,chunks=2,dim=1)
print(b)

tensor([[0.2568, 0.8291],
        [0.5609, 0.9310],
        [0.8685, 0.7991]])
(tensor([[0.2568, 0.8291],
        [0.5609, 0.9310]]), tensor([[0.8685, 0.7991]]))
(tensor([[0.2568],
        [0.5609],
        [0.8685]]), tensor([[0.8291],
        [0.9310],
        [0.7991]]))
